
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 10 02:02:20 MST 2015
//----------------------------------------------------

package NohtypPackage;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int tigualmayor = 22;
  public static final int trange = 36;
  public static final int tigual = 23;
  public static final int tmas = 14;
  public static final int tin = 10;
  public static final int tor = 31;
  public static final int tabrep = 28;
  public static final int tif = 9;
  public static final int tpor = 16;
  public static final int tid = 43;
  public static final int tstr = 40;
  public static final int tmodulo = 18;
  public static final int txinput = 2;
  public static final int tmenos = 15;
  public static final int tmenor = 32;
  public static final int tint = 44;
  public static final int txarray = 42;
  public static final int tabrec = 26;
  public static final int tpuntos = 34;
  public static final int tfor = 8;
  public static final int tmayor = 33;
  public static final int ttrue = 4;
  public static final int tnot = 11;
  public static final int tand = 5;
  public static final int tcoma = 30;
  public static final int tabre = 24;
  public static final int tpunto = 35;
  public static final int EOF = 0;
  public static final int twhile = 12;
  public static final int error = 1;
  public static final int tstring = 46;
  public static final int treal = 45;
  public static final int telse = 7;
  public static final int tcierrap = 29;
  public static final int tfalse = 3;
  public static final int tentre = 17;
  public static final int tcierra = 25;
  public static final int tprint = 39;
  public static final int tigualque = 19;
  public static final int tcierrac = 27;
  public static final int telif = 6;
  public static final int tdiferente = 20;
  public static final int tinput = 38;
  public static final int tpuntocoma = 37;
  public static final int tcomentarios = 13;
  public static final int tigualmenor = 21;
  public static final int tarray = 41;
  public static final int tchar = 47;
}

